### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by Xiefan-Guo** [jingyuanli001/RFR-Inpainting#12]
Hi, thanks for your work.
I have some problems on CelebA.

```
Traceback (most recent call last):
  File "F:/PyTorch-CV/RFR-Inpainting-master/test.py", line 39, in <module>
    run()
  File "F:/PyTorch-CV/RFR-Inpainting-master/test.py", line 29, in run
    model.initialize_model(args.model_path, False)
  File "F:\PyTorch-CV\RFR-Inpainting-master\model_test.py", line 31, in initialize_model
    start_iter = load_ckpt(path, [('generator', self.G)], [('optimizer_G', self.optm_G)])
  File "F:\PyTorch-CV\RFR-Inpainting-master\utils\io.py", line 25, in load_ckpt
    ckpt_dict = torch.load(ckpt_name)
  File "E:\anaconda\anaconda\envs\pytorch_gpu\lib\site-packages\torch\serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\anaconda\anaconda\envs\pytorch_gpu\lib\site-packages\torch\serialization.py", line 704, in _legacy_load
    deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: pickle data was truncated
```

**Comment by jingyuanli001** [comment]
Hi,

Thank you for your question.
Sorry for the late response. 
I've checked the CelebA pertained model and it turns out that the model file is damaged when I was uploading it to google cloud. I will upload an alternative one this week.

Thank you!
