### ISSUE TITLE
测试的错误

### ISSUE THREAD

**Issue by zhangshilong2000** [jingyuanli001/RFR-Inpainting#74]
Model moved to cuda
Traceback (most recent call last):
  File "run.py", line 38, in <module>
    run()
  File "run.py", line 30, in run
    model.test(dataloader, args.result_save_path)
  File "E:\ZSL\code\RFR-Inpainting-master\model.py", line 88, in test
    fake_B, mask = self.G(masked_images, masks)
  File "D:\anaconda\envs\MT\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\ZSL\code\RFR-Inpainting-master\modules\RFRNet.py", line 146, in forward
    x1, m1 = self.Pconv1(in_image, mask)
  File "D:\anaconda\envs\MT\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\ZSL\code\RFR-Inpainting-master\modules\partialconv2d.py", line 66, in forward
    raw_out = super(PartialConv2d, self).forward(torch.mul(input, mask) if mask is not None else input)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1
这个错误是由什么原因导致？

**Comment by 7423cg** [comment]
原始图片和掩码图片大小不一样？
